# [ Font Options ]
font:
  normal:
    family: "Fira Code"
    style: Regular
      
  bold:
    family: "Fira Code"
    style: Medium
 
  italic:
    family: "Fira Code" 
    style: "Light Italic"
  
  size: 8.5

# [ Window Options ]
window:
  padding:
    x: 10
    y: 10
      
scrolling: 
  history: 1000

# [ Colors ]
background_opacity: 0.95 

colors:
  # Default colors
  primary:
    background: '0x1d1f21'
    foreground: '0xbbc5ff'

  # Normal colors
  normal:
    black:   '0x101010'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xd0d0d0'

  # Bright colors
  bright:
    black:   '0x434758'
    red:     '0xff8b92'
    green:   '0xddffa7'
    yellow:  '0xffe585'
    blue:    '0x9cc4ff'
    magenta: '0xe1acff'
    cyan:    '0xa3f7ff'
    white:   '0xffffff' 
