#!/bin/bash

# IMPORTANT!!
# You have to source this script when running it

# $source PATH_TO_THIS_SCRIPT ALIAS DIR
# to make it easier just make an alias for it.
# put this in your .bashrc/.zshrc:
# alias to="source PATH_TO_THIS_SCRIPT"

_aliases="$HOME/.config/to_aliases.txt"
_alias="$1"

[ ! -f $_aliases ] && touch $_aliases

get_alias() {
	[ ! -z $2 ] \
		&& (cat "$_aliases" | grep "^${_alias}" | cut -d$'\t' -f${1},${2})\
		|| (cat "$_aliases" | grep "^${_alias}" | cut -d$'\t' -f${1})
}

replace() {
	[ ! $(get_alias 1) ] && exit
	name=$(get_alias 1)
	key=$(echo $1)
	sed -i "s+^\($name\).*+\1\t$1+" $_aliases
	echo "updated alias $name -> $key !"
}

goto() {
	cd $(get_alias 2)
}

if [[ $(get_alias 1) ]]; then
	[ -z $2 ]	&& goto || replace $2
else
	[ -z $2 ] && echo alias not found, and second argument was not provided! && exit
	echo -e "$1\t$2" >> "$_aliases"
	echo "alias created! $1 -> $2"
fi
