#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh --shapes &
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width            3
bspc config window_gap              12
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
bspc config presel_border_color "$color1"	
#bspc config normal_border_color     "#30302f"
#bspc config focused_border_color    ${xrdb:color7}
bspc config focus_follows_pointer true
bspc config top_padding             40
bspc config bottom_padding          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a emacs state=tiling
bspc rule -a Komikku state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a kitty state=floating
bspc rule -a gotroller-gui state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
