#!/bin/sh
# _   _    _    ____    _    _   _ 
#| | | |  / \  / ___|  / \  | \ | |
#| |_| | / _ \ \___ \ / _ \ |  \| |
#|  _  |/ ___ \ ___) / ___ \| |\  |
#|_| |_/_/   \_\____/_/   \_\_| \_|

gap=$(bspc config window_gap)
increase=10

more=`expr $gap + $increase`
Less=`expr $gap - $increase`

if [[ -z $1 ]]; then
echo "you need to provide an argument:
more, less or default"
fi

if [[ $1 == "more" ]]; then
    bspc config window_gap $more
    echo $more
fi

if [[ $1 == "less" ]]; then
    bspc config window_gap $Less
    echo $Less
fi

if [[ $1 == "default" ]]; then
    bspc config window_gap 20
    echo 20
fi
