#!/bin/bash

#
# All credits to :
#===============================================================#
# Author:   	  Abanoub Asaad			   						#
# Version:   	  0.1				     				     	#
# My GitHub:	  https://github.com/Abanoub-Asaad    	        #
# Note:		  	  This script depends completely on IMDb  	 	#
#===============================================================#

#                     _ _  __ _          _   _             _                           
# _ __ ___   ___   __| (_)/ _(_) ___  __| | | |__  _   _  | |__   __ _ ___  __ _ _ __  
#| '_ ` _ \ / _ \ / _` | | |_| |/ _ \/ _` | | '_ \| | | | | '_ \ / _` / __|/ _` | '_ \ 
#| | | | | | (_) | (_| | |  _| |  __/ (_| | | |_) | |_| | | | | | (_| \__ \ (_| | | | |
#|_| |_| |_|\___/ \__,_|_|_| |_|\___|\__,_| |_.__/ \__, | |_| |_|\__,_|___/\__,_|_| |_|
#                                                  |___/               

# Download the resultant web page for the specified search
wget -O "$1-search.html" "http://www.imdb.com/find?q=$1" 2>/dev/null


# Run another regex to get the movie titles div and write the data to another file to avoid link filename mismatch
sed -e '/Titles<\/h3>/,/findMoreMatches/!d' "$1-search.html" > "partialContentFile.txt"


# Get the resultant movies' sub links from a html file
grep -E -o "\/title\/[a-zA-Z0-9]+\/" "partialContentFile.txt" > "filesToDownload.txt"


# Get the resultant movies' names
grep -P -o "(?<=>)([a-zA-Z0-9&: _-]+)(?=<\/a>[\(\) a-zA-Z0-9 _-]*\([0-9]+\))" "partialContentFile.txt" > "movieNames.txt"


# Get the result movies' years
grep -P -o "(?<=<\/a> )(\([0-9]+\))(?= )" "partialContentFile.txt" > "movieYears.txt"


# Make a new file to store the movie names and years
> "movieNameYear.txt"


# Use different file descriptors to read from two files and combine them in "movieNameYear.txt file"
while read -r -u3 movieName; read -r -u4 movieYear;
do
 echo "$movieName" "$movieYear" >> "movieNameYear.txt"
done 3<movieNames.txt 4<movieYears.txt


# Read from the file that was written to and store in the names and years in an array 
j=0 

while read line
do
	repline=$line
	
	# Replace file name spaces with underscore
	fixedline=${repline// /_}	
	movieNameYear_array[j]=$fixedline
	#echo ${movieNameYear_array[j]}
	j=$(( j + 1 ))
done < "movieNameYear.txt"



# Since the link are duplicated because of the link of title and the link of image, so I filter them here 
moviefoldername=movies

mkdir $moviefoldername

i=0
k=0

while read line
do
	temp=$(( $i % 2 )) 
	
	# Temporary fix when file name or file year was not extracted correctly 
	if [ $j -eq $k ]; then
		break
	fi
	
	if [ $temp -eq 0 ]; then
		
		# Each of the resultant files are downloaded here, Now read and perform rating extraction from it
		wget -O "$moviefoldername/${movieNameYear_array[k]}" "http://www.imdb.com$line" 2>/dev/null
		k=$(( k + 1 ))

	fi

	i=$(( i + 1 ))

done < "filesToDownload.txt"




# The Output here :)
for fileName in `ls $moviefoldername/`
do
    grep 'meta name="description" content="' "$moviefoldername/$fileName"  | cut -d '"' -f4 >> /tmp/grepped
    grep 'meta name="description" content="' "$moviefoldername/$fileName"  | cut -d '"' -f4 >> /tmp/grepped2

    echo "------------------------------------------------"
	tput setaf 4; echo "Original name and Year of Release: "
	tput setaf 7; echo "$fileName"	

	#<span itemprop="ratingValue">6.4</span></strong>
	tput setaf 4; echo "Rating: ";
	tput setaf 3;
	grep -P -o "(?<=<span itemprop=\"ratingValue\">)([0-9][.]?[0-9]?)(?=<\/span><\/strong>)" "$moviefoldername/$fileName"
	tput setaf 4; echo "Director and Stars: " 
    tput setaf 7; vim -c ":g/^/norm 2f.d$" -c ":wq" /tmp/grepped2
    grep -v "#" /tmp/grepped2
    rm /tmp/grepped2
    tput setaf 4; echo "Story Synopsis: "
    tput setaf 3; vim -c ":g/^/norm 2f.2ld0" -c ":wq" /tmp/grepped
    grep -v "#" /tmp/grepped
    rm /tmp/grepped
    tput sgr 0 ; echo "------------------------------------------------"
done
	


# Make directory to put in it all related files
if [[ -d Sermov\ Fetcher\ related ]]
then
    rm -r Sermov\ Fetcher\ related
    mkdir Sermov\ Fetcher\ related
else
    mkdir Sermov\ Fetcher\ related
fi

# Move all related files to directory "Sermov_Fetcher_related"
mv "$1-search.html" Sermov\ Fetcher\ related
mv "partialContentFile.txt" Sermov\ Fetcher\ related
mv "filesToDownload.txt" Sermov\ Fetcher\ related
mv "movieNames.txt" Sermov\ Fetcher\ related
mv "movieYears.txt" Sermov\ Fetcher\ related
mv "movieNameYear.txt" Sermov\ Fetcher\ related
mv movies Sermov\ Fetcher\ related

# Remove the whole directory which contains the used files and the tmp files
rm -r Sermov\ Fetcher\ related

# Change the terminal color to the default "White"
tput setaf 7;
