#!/bin/sh
##_   _    _    ____    _    _   _ 
#| | | |  / \  / ___|  / \  | \ | |
#| |_| | / _ \ \___ \ / _ \ |  \| |
#|  _  |/ ___ \ ___) / ___ \| |\  |
#|_| |_/_/   \_\____/_/   \_\_| \_|
                                  



while true
do
myWall=$(find $1 | shuf | head -n 1) 
#feh --bg-fill $myWall
killall polybar
bash ~/.config/polybar/shapes/scripts/pywal.sh  "$myWall"
bash ~/.config/polybar/launch.sh --shapes
sleep 10m
done
