#!/bin/sh

myFILE="$HOME/.cache/watchlist"

[ ! -f "$myFILE" ] && touch "$myFILE"

myLIST(){
    printf %35s |tr " " "="
    echo -e "\n"
    paste <(cut -d '|' -f1 $myFILE) <(cut -d'|' -f2 $myFILE) | awk -v FS='\t' '{printf("%-30s %s\n",$1,$2)}' | awk '{sub(/^/, " ", $0)}1' | sed "0~1 a\ $(printf %32s |tr " " " ") \ "
    printf %35s |tr " " "="
    echo ""
}

watchAnime(){
if [[ -z $1 ]]; then
    Select=`cat "$myFILE" | cut -d '|' -f1 | fzy`
    [ -z "$Select" ] && echo "nothing selected." && exit

    currentEP=$(grep "$Select" $myFILE | cut -d '|' -f 2)
    EP=`expr "$currentEP" + 1 `
    myChoice=$(grep "$Select" $myFILE | cut -d '|' -f 3)

    if [[ $myChoice == "0" ]]; then
        echo -e "PLEASE REMEMBER WHICH NUMBER YOU WILL SELECT RIGHT NOW!"
        sleep 1s
        echo "playing $Select ep num. $EP"
        anime dl "$Select" -e "$EP"
        echo "what was the anime number that you selected?"
        read NUMBER
        sed -i "s/^$Select.*/$Select|$currentEP|$NUMBER/" "$myFILE"

    else
        echo "playing $Select ep num. $EP"
        anime dl "$Select" -e "$EP" -c $myChoice
    fi

    echo "mark as watched?"
    read MARK
    [ $MARK == y ] || [ -z $MARK ] &&\
        sed -i "s/^$Select|$currentEP/$Select|$EP/" "$myFILE"
        echo "marked ep num. $EP as watched!" \
        || echo "didn't mark ep num. $EP as watched."

else
    if [[ -z $3 ]]; then
        [ -z "$2" ] && echo ""$1"|0|0|watching" >> "$myFILE"\
            || echo ""$1"|"$2"|0|watching" >> "$myFILE"\
            && echo "Added Anime to Watchlist!"
    else
        [ -z "$2" ] && echo ""$1"|0|0|"$3"" >> "$myFILE"\
            || echo ""$1"|"$2"|0|"$3"" >> "$myFILE"\
            && echo "Added Anime to Watchlist!"
    fi
fi
}

loop(){ 
    while true; do
    watchAnime
    done
}

case "$1" in
    -e ) vim "$myFILE" ; exit ;;
    -l ) myLIST ; exit ;;
    -p ) loop "$@" ;;
    *) watchAnime "$@" ;;
esac
