#!/bin/sh

# Clean up if script got cancelled
__cleanup(){
	rm names.tmp 2>/dev/null
	rm book.html 2>/dev/null
}

trap __cleanup EXIT

# Search Query
echo "What is the name of the book?"
read name
echo "language:"
read LANG

query=$(echo $name| sed 's/\ /+/g')
url="http://libgen.rs/search.php?req=${query}&open=0&res=100&view=simple&phrase=1&column=def"
wget -O 'book.html' $url 2>/dev/null

# Output
echo "-------------------------------------------------------------------------------"
cat --number <<< $(grep -B10 -i "<td>$LANG" book.html | awk '{FS="[><]"}{gsub(/\[[0-9].*/,"");}/id=/{print$5}'\
	| sed '/^$/d') | tee names.tmp
echo "-------------------------------------------------------------------------------"

# Choose the book number
echo "Pick a number"
read NUM

# The book's name
my_book=$(grep "^[[:space:]]*$NUM[[:space:]]" names.tmp)
__book=$(echo $my_book | sed 's/^[0-9]*[[:space:]]//g')

# Download the book
wget $(curl $(grep -B10 -i "<td>$LANG" book.html | grep -A10 "$__book"| awk '{FS="[><]"}/title=.Gen.lib.rus.ec./{print $12}' |\
	cut -d"'" -f2) 2>/dev/null | awk '{FS="\""}/GET/{print$8}' | sed 's/^/libgen.lc/g') \
	-O "$__book"

# clean up
rm book.html
rm names.tmp
