#!/bin/sh

#===================================
# _   _    _    ____    _    _   _ #
#| | | |  / \  / ___|  / \  | \ | |#
#| |_| | / _ \ \___ \ / _ \ |  \| |#
#|  _  |/ ___ \ ___) / ___ \| |\  |#
#|_| |_/_/   \_\____/_/   \_\_| \_|#
#                                  #
#===================================

#### [functions]
# search google for myanimelist
mySearch(){
    SEARCH=$@
    URL="http://google.com/search?hl=en&safe=off&q="
    STRING=`echo $SEARCH | sed 's/ /+/g'`
    URI="$URL$STRING"
    
    lynx -dump $URI > raw.tmp
    sed 's/http/\^http/g' raw.tmp | tr -s "^" "\n" | grep http| sed 's/\ .*//g' > modified.tmp
    rm raw.tmp
    sed '/google.com/d' modified.tmp > urls
    rm modified.tmp
    
    echo ""
    cat urls
    echo ""
}

mySeason(){
    [ -z "$2" ] | [ -z "$3" ] && echo "usage: $(tput setaf 7)mal $(tput setaf 3)-s $(tput setaf 2)[season]$(tput setaf 4) [year]"
    curl "https://myanimelist.net/anime/season/"$3"/"$2"" 2>/dev/null | grep "h2_anime_title" | cut -d '>' -f 3 | cut -d '<' -f 1 | awk '{print NR  " " $s}' | sort -V -k1 -r ;
}

topList(){
    [ -z "$2" ] && echo "usage: $(tput setaf 7)mal $(tput setaf 3)-t $(tput setaf 2)anime$(tput setaf 7)/$(tput setaf 4)manga "

    mySep=$(printf %80s |tr " " "-")
    paste\
        <( (curl "https://myanimelist.net/top"$2".php" && curl "https://myanimelist.net/top"$2".php?limit=50") 2>/dev/null\
        | grep "hoverinfo_trigger fl-l ml12 mr8" | cut -d '"' -f 4 | cut -d '/' -f 6  | sed 's/_/ /g' | awk '{print NR "]  " $s}'|  sort -V -k1 -r  | sed 's/^/[/g' )\
        \
        <( (curl "https://myanimelist.net/top"$2".php" && curl "https://myanimelist.net/top"$2".php?limit=50") 2>/dev/null\
        | grep "js-top-ranking-score-col di-ib al" | cut -d ">" -f 6 | cut -d "<" -f 1 | sort -V -k1)\
        \
        | awk -v FS='\t' '{printf("%-75s %s\n",$1,$2)}' | awk '{sub(/^/, " ", $0)}1' | sed "0~1 a\ "$mySep" \ " 
}

helpMe(){
        echo " Usage: mal <flag> [NAME]

    -h | --help ) displays this help message
    -t | --top ) list of 100 top manga/anime
    -s | --season ) list of anime in any season any year"; }

# flags
case "$1" in
    -s | --season ) mySeason "$@" ; exit ;;
    -t | --top ) topList "$@" ; exit ;;
    -h | --help ) helpMe ; exit ;;
esac

# bts
(mySearch ""$@" myanimelist") >/dev/null

(curl $(cat urls | head -n1 ) | html2text > raw.txt) 2>/dev/null

rm urls

sed -n '/More\ reviews/q;p' raw.txt > page.txt

rm raw.txt

myWord="$(cat page.txt | grep 'Synopsis' -A 2 | tail -n1 | cut -d ' ' -f 1-6)"

# cover photo
myType=$(grep "Type:" page.txt | cut -d '[' -f 2 | cut -d ']' -f 1)

if [[ $myType == "Manga" ]]; then
    (curl $(cat page.txt | grep -i "pictures" | cut -d '(' -f 2 | sed 's/)//' | sed 's|^|https://myanimelist.net|g') | html2text > pics) 2>/dev/null
else
    (curl $(cat page.txt | grep -i "pictures" | cut -d '(' -f 2 | sed 's/)//') | html2text > pics) 2>/dev/null
fi
(curl $(cat pics | grep -i "jpg" | cut -d '(' -f 2 | cut -d ' ' -f1 | sed 1d | head -n1) | imv - &) 2>/dev/null


# output
echo -e "$(tput setaf 2)---------------------------------------"

echo -e "Title:$(grep -iF "ALternative Titles" -A 2 page.txt | tail -n1 | sed 's/English://g')"
echo -e "$(tput setaf 3)\b"

grep -iF "score:" page.txt | tail -n1
echo -e "\b"

grep -iF "ranked:" page.txt | tail -n1
echo -e "$(tput setaf 2)---------------------------------------"
echo -e "$(tput setaf 7)\b"

echo "Synopsis:"
echo -e "$(tput setaf 7)\b"
awk -v RS='' "/$myWord/" page.txt 

echo -e "$(tput setaf 2)---------------------------------------"
echo -e "$(tput setaf 6)"

grep -iF "information" -A 30 page.txt | grep -iv "produc" | sed -n "/Serialization/q;p" | sed -n "/--/q;p"| sed "s/([^)]*)//g" | sed 1,2d | cat -s
echo -e "$(tput setaf 2)---------------------------------------"

rm page.txt
rm pics
