#!/bin/sh

#===================================
# _   _    _    ____    _    _   _ #
#| | | |  / \  / ___|  / \  | \ | |#
#| |_| | / _ \ \___ \ / _ \ |  \| |#
#|  _  |/ ___ \ ___) / ___ \| |\  |#
#|_| |_/_/   \_\____/_/   \_\_| \_|#
#                                  #
#===================================

#### [functions]
# search google for myanimelist
mySearch(){
    SEARCH=$@
    URL="http://google.com/search?hl=en&safe=off&q="
    STRING=`echo $SEARCH | sed 's/ /+/g'`
    URI="$URL$STRING"
    
    lynx -dump $URI > raw.tmp
    sed 's/http/\^http/g' raw.tmp | tr -s "^" "\n" | grep http| sed 's/\ .*//g' > modified.tmp
    rm raw.tmp
    sed '/google.com/d' modified.tmp > urls
    rm modified.tmp
    
    echo ""
    cat urls
    echo ""
}

# flags
case "$1" in
    -s | --season ) curl "https://myanimelist.net/anime/season/"$3"/"$2"" 2>/dev/null | grep "h2_anime_title" | cut -d '>' -f 3 | cut -d '<' -f 1 | awk '{print NR  " " $s}' | sort -V -k1 -r ; exit ;;
    -h | --help ) echo "dude, it's obvious." ; exit ;;
esac

# bts
(mySearch ""$@" myanimelist") >/dev/null

wget -O "$@" $(cat urls | head -n1 ) 2>/dev/null


html2text "$@" > removereviews"$@".txt 
sed -n '/More\ reviews/q;p' removereviews"$@".txt > html2text"$@".txt

myWord="$(cat html2text"$@".txt | grep 'Synopsis' -A 2 | tail -n1 | cut -d ' ' -f 1-6)"

# cover photo
myType=$(grep "Type:" html2text"$1".txt | cut -d '[' -f 2 | cut -d ']' -f 1)

if [[ $myType == "Manga" ]]; then
    wget -O pics $(cat html2text"$1".txt | grep -i "pictures" | cut -d '(' -f 2 | sed 's/)//' | sed 's|^|https://myanimelist.net|g') 2>/dev/null
else
    wget -O pics $(cat html2text"$1".txt | grep -i "pictures" | cut -d '(' -f 2 | sed 's/)//') 2>/dev/null
fi
html2text pics > pics2text
(curl $(cat pics2text | grep -i "jpg" | cut -d '(' -f 2 | cut -d ' ' -f1 | sed 1d | head -n1) | imv -c ":zoom -7" - &) 2>/dev/null

# output
echo -e "$(tput setaf 2)---------------------------------------"

echo -e "Title:$(grep -iF "ALternative Titles" -A 2 html2text"$@".txt | tail -n1 | sed 's/English://g')"
echo -e "$(tput setaf 3)\b"
grep -iF "score:" html2text"$1".txt | tail -n1
echo -e "\b"
grep -iF "ranked:" html2text"$1".txt | tail -n1
echo -e "$(tput setaf 2)---------------------------------------"

echo -e "$(tput setaf 7)\b"
echo "Synopsis:"
echo -e "$(tput setaf 7)\b"
awk -v RS='' "/$myWord/" html2text"$@".txt 
echo -e "$(tput setaf 2)---------------------------------------"

echo -e "$(tput setaf 6)"
grep -iF "information" -A 30 html2text"$1".txt | grep -iv "produc" | sed -n "/Serialization/q;p" | sed -n "/--/q;p"| sed "s/([^)]*)//g" | sed 1,2d | cat -s
echo -e "$(tput setaf 2)---------------------------------------"

# delete trash
rm urls
rm "$@"
rm removereviews"$@".txt
rm html2text"$@".txt
rm pics
rm pics2text
